// Auto-generated by scripts/generate-ts-embeddings.mjs
// DO NOT EDIT MANUALLY - regenerate using: node scripts/generate-embeddings.mjs && node scripts/generate-ts-embeddings.mjs

export interface ClusterInfo {
  id: number;
  color: string;
  nodeIds: string[];
}

export const clusterPalette = [
  '#8CCB9B', // Cluster 0: Green - TV/Sports/Tech/Social
  '#F5C06E', // Cluster 1: Yellow - Food/Dining/Shows
  '#9C8ADE', // Cluster 2: Purple - Music/Arts/Travel
  '#74A8E4', // Cluster 3: Blue - Fitness/Health
  '#E7A26F', // Cluster 4: Orange - Lifestyle/Decor/Tech
  '#F28B82', // Cluster 5: Red - Wellness/Fitness
];

export const clusters: ClusterInfo[] = [
  {
    id: 0,
    color: '#8CCB9B',
    nodeIds: [
      'n3', 'n8', 'n15', 'n16', 'n18', 'p10', 'p12', 'p14',
      'p27'
    ]
  },
  {
    id: 1,
    color: '#F5C06E',
    nodeIds: [
      'n11', 'n12', 'n13', 'n14', 'n19', 'n32', 'n35', 'p3',
      'p8', 'p13', 'p16', 'p17', 'p19'
    ]
  },
  {
    id: 2,
    color: '#9C8ADE',
    nodeIds: [
      'n4', 'p15'
    ]
  },
  {
    id: 3,
    color: '#74A8E4',
    nodeIds: [
      'n6', 'n7', 'n9', 'n10', 'n30', 'p4', 'p5', 'p6',
      'p7', 'p9', 'p18'
    ]
  },
  {
    id: 4,
    color: '#E7A26F',
    nodeIds: [
      'n1', 'n5', 'n17', 'n20', 'n22', 'n23', 'n24', 'n33',
      'n34', 'p1', 'p2', 'p11', 'p20', 'p21'
    ]
  },
  {
    id: 5,
    color: '#F28B82',
    nodeIds: [
      'n2', 'n21', 'n25', 'n26', 'n27', 'n28', 'n29', 'n31',
      'p22', 'p23', 'p24', 'p25', 'p26'
    ]
  }
];

export function getClusterColor(clusterId: number): string {
  return clusterPalette[clusterId] || clusterPalette[0];
}

// Manual cluster category metadata for UI display
// Labels based on actual K-Means clustering results from embeddings-output.json
export interface ClusterCategory {
  id: number;
  name: string;
  color: string;
  examples: string[];
}

export const clusterCategoryMetadata: ClusterCategory[] = [
  { 
    id: 0, 
    name: "Food & Entertainment", 
    color: "#8CCB9B", 
    examples: ["Baking", "Netflix Shows", "Wine Tasting"]
  },
  { 
    id: 1, 
    name: "Adventures", 
    color: "#F5C06E", 
    examples: ["Travel Destinations", "Interior Design", "Hiking Trails"]
  },
  { 
    id: 2, 
    name: "Health & Wellness", 
    color: "#9C8ADE", 
    examples: ["Protein Recipes", "Taco Tuesday"]
  },
  { 
    id: 3, 
    name: "Sports & Music", 
    color: "#74A8E4", 
    examples: ["The Bear", "Warriors Games", "Taylor Swift"]
  },
  { 
    id: 4, 
    name: "Lifestyle", 
    color: "#E7A26F", 
    examples: ["Home Workouts", "Yoga", "Indie Music"]
  },
  { 
    id: 5, 
    name: "Photography", 
    color: "#F28B82", 
    examples: ["Concert Photos", "iPhone", "Tech"]
  },
];
