// Auto-generated by scripts/generate-ts-embeddings.mjs
// DO NOT EDIT MANUALLY - regenerate using: node scripts/generate-embeddings.mjs && node scripts/generate-ts-embeddings.mjs

export interface ClusterInfo {
  id: number;
  color: string;
  nodeIds: string[];
}

export const clusterPalette = [
  '#8CCB9B', // Cluster 0: Green - TV/Sports/Tech/Social
  '#F5C06E', // Cluster 1: Yellow - Food/Dining/Shows
  '#9C8ADE', // Cluster 2: Purple - Music/Arts/Travel
  '#74A8E4', // Cluster 3: Blue - Fitness/Health
  '#E7A26F', // Cluster 4: Orange - Lifestyle/Decor/Tech
  '#F28B82', // Cluster 5: Red - Wellness/Fitness
];

export const clusters: ClusterInfo[] = [
  {
    id: 0,
    color: '#8CCB9B',
    nodeIds: [
      'n8', 'n24', 'n26', 'n27', 'n30', 'p4', 'p5', 'p6',
      'p18', 'p24', 'p25'
    ]
  },
  {
    id: 1,
    color: '#F5C06E',
    nodeIds: [
      'n6', 'n7', 'n10', 'n16', 'n17', 'n25', 'n28', 'p1',
      'p2', 'p10', 'p13', 'p14', 'p15', 'p26', 'p27'
    ]
  },
  {
    id: 2,
    color: '#9C8ADE',
    nodeIds: [
      'n12', 'n13', 'n15', 'n18', 'n21', 'n23', 'n32', 'p3',
      'p8', 'p9', 'p16', 'p23'
    ]
  },
  {
    id: 3,
    color: '#74A8E4',
    nodeIds: [
      'n4', 'n14', 'p21'
    ]
  },
  {
    id: 4,
    color: '#E7A26F',
    nodeIds: [
      'n2', 'n5', 'n11', 'n19', 'n29', 'n31', 'n34', 'p7',
      'p11', 'p22'
    ]
  },
  {
    id: 5,
    color: '#F28B82',
    nodeIds: [
      'n1', 'n3', 'n9', 'n20', 'n22', 'n33', 'n35', 'p12',
      'p17', 'p19', 'p20'
    ]
  }
];

export function getClusterColor(clusterId: number): string {
  return clusterPalette[clusterId] || clusterPalette[0];
}
